# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ERROR PREVENTION
    avoid_print: true # Prevents leaving print() statements in production code
    always_declare_return_types: true # Forces you to specify what a function returns
    cancel_subscriptions: true # Warns if you forget to close a Stream (prevents memory leaks)
    close_sinks: true # Similar to above, for StreamControllers
    
    # STYLE & READABILITY
    always_use_package_imports: true # Forces absolute imports (package:nexus/...) instead of relative (../../)
    camel_case_types: true # Classes should be PascalCase (e.g., UserProfile)
    file_names: true # Files should be snake_case (e.g., user_profile.dart)
    
    # PERFORMANCE
    prefer_const_constructors: true # Crucial for Flutter UI performance
    prefer_const_declarations: true # Uses less memory for variables that don't change
    prefer_final_locals: true # Makes code more predictable
    
    # FLUTTER SPECIFIC
    use_key_in_widget_constructors: true # Helps Flutter recognize widgets in the tree
    sized_box_for_whitespace: true # Suggests SizedBox instead of Container (it's cheaper/faster)
    use_build_context_synchronously: true # Prevents using BuildContext after an async gap (common crash cause)

analyzer:
  exclude:
    - "**/*.g.dart" # Ignore generated files (we will use these later for Freezed/JSON)
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore # Required for some modern code generation tools